.huskyrc
.prettierrc
commitlint.config.js
package.json
src/App.js
yarn.lock

add prettier, pretty-quick, husky, commitlint, and related scripts and files
closes #3

chore: set up remaining development environment

---

package.json
src/components/App.js
src/components/Root.js
src/index.js
yarn.lock

add materialUI dependencies, and prop-types for typechecking
closes #7

feat: add @materialUI and prop-types

---

package.json
src/components/Root.js
src/config/env.js
src/config/i18n.js
src/langs/en.json
src/langs/fr.json
yarn.lock

chore: add final app scaffolding

---

.gitignore
package.json

chore: add authors to package.json

---

README.md

docs: add title to readme

---

src/api/graasp.js

taking into account upcoming changes to graasp-service-analytics
closes #46

chore: update api endpoint

---

package.json
src/api/graasp.js
src/components/common/Loader.js
src/components/custom/CustomValueContainer.js
src/components/space/ActionsChart.js
src/components/space/ActionsMap.js
src/components/space/Charts.js
src/components/space/UsersSelect.js
src/config/constants.js
src/config/i18n.js
src/contexts/SpaceDataProvider.js
src/langs/en.json
src/utils/api.js
yarn.lock

using react-select; we can now see all users of a space, and display actions of selected users
fixes #48

feat: add functionality to filter/display actions by user

---

src/components/custom/CustomTooltip.js
src/components/custom/CustomValueContainer.js
src/components/space/ActionsByDayChart.js
src/components/space/ActionsByTimeOfDayChart.js
src/components/space/ActionsByVerbChart.js
src/components/space/ActionsMap.js
src/components/space/Charts.js
src/components/space/EmptyChart.js
src/config/constants.js
src/utils/api.js
yarn.lock

feat: add additional charts ActionsByTimeOfDay and ActionsByVerb

---

src/config/constants.js
src/contexts/SpaceDataProvider.js
src/utils/api.js

feat: remove 'user' Learning Analytics from users list

---

src/components/space/ChartsLayout.js
src/components/space/charts-layout/ChartsArea.js
src/components/space/charts/ItemsByAccessedCount.js
src/config/constants.js
src/utils/api.js

feat: add chart showing most viewed items in compose view

---

.github/workflows/cdelivery-s3-caller.yml
.github/workflows/cdeployment-s3-caller.yml
.github/workflows/cintegration-s3-caller.yml
CHANGELOG.md
package.json
scripts/deploy.sh
yarn.lock

refactor: rename repository and files

---

package.json

refactor: add release commands

---

src/utils/api.js

This pr changes the way to extract the date and the time information. We now extract the date and the time information from a Date object instead of slicing from the time string.

fix: fix date extracting approach

---

src/components/App.js
src/components/pages/ItemPage.tsx
src/components/sidebar/Sidebar.tsx
src/config/paths.ts
src/langs/en.json

feat: add sidebar

---

package.json
src/components/layout/Header.js
src/config/constants.ts
yarn.lock

137 navigation toggles

---

src/components/space/charts/ActionsByDayChart.tsx
src/utils/utils.ts

This PR fixes some type issues in utility functions.

fix: types

---

.github/workflows/build.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml

- fix #158 and update workflows
- fix: add a build workflow to check that everything is alright

fix: add GA tracking 

---

src/components/space/functionality/ViewSelect.tsx

fix: translate tooltip at view selection

---

cypress/e2e/selectView.cy.ts
src/components/context/ViewDataProvider.tsx
src/components/space/functionality/ViewSelect.tsx
src/config/selectors.ts

In this PR I fix a bug I introduced:
- can't select a view in the view select because the passed value is checked agains keys and not values
- add a regression test to ensure feature works

fix: can't select a view

---

src/utils/utils.ts

I think the second chart (action nb per day) is anomaly flat for personal count.

fix: fix date chart

---

src/components/space/charts/ActionsMap.tsx
src/langs/en.json

fix: don't display map if there's no geolocation actions

---

src/components/space/charts-layout/ChartsHeader.tsx
src/components/space/functionality/ActionsSelect.tsx
src/components/space/functionality/UsersSelect.tsx
src/components/space/functionality/ViewSelect.tsx

feat: use autocomplete for both user and actions select

---

package.json
src/components/context/DataProvider.tsx
src/components/space/charts/ActionsByVerbChart.tsx
src/components/space/charts/ItemsByActionChart.tsx
src/components/space/charts/TotalActionsByVerbChart.tsx
src/components/space/charts/UsersByActionChart.tsx
src/config/constants.ts
src/utils/utils.ts
yarn.lock

feat: unify action colors

---

src/components/App.tsx
src/components/layout/Sidebar.tsx
src/components/pages/Item/ExportAnalyticsPage.tsx
src/components/pages/Item/GeneralAnalyticsPage.tsx
src/components/pages/Item/ItemPage.tsx
src/components/space/functionality/ExportData.tsx
src/config/i18n.ts
src/config/notifier.tsx
src/config/paths.ts
src/langs/en.json

feat: separate export item in a route

---

src/components/App.tsx
src/components/Root.tsx
src/langs/en.json

fix: redirect to login if user not logged in

---

src/components/layout/Navigator.tsx

fix: home navigation is always for home path

---

cypress/e2e/chartsHeader.cy.ts
cypress/e2e/selectView.cy.ts
cypress/fixtures/members.ts
src/components/App.tsx
src/components/layout/PageWrapper.tsx
src/components/layout/Sidebar.tsx
src/components/pages/Item/GeneralAnalyticsPage.tsx
src/components/pages/Item/ItemAnalyticPage.tsx
src/components/pages/Item/ItemPage.tsx
src/components/pages/Item/UsersAnalyticPage.tsx
src/components/space/functionality/ActionsSelect.tsx
src/components/space/functionality/UsersSelect.tsx
src/config/selectors.ts

feat: maintain selects values over routes

---

package.json
src/components/Root.tsx
src/components/common/ChartContainer.tsx
src/components/space/charts/ActionsByDayChart.tsx
src/components/space/charts/ActionsByTimeOfDayChart.tsx
src/components/space/charts/ActionsByUserChart.tsx
src/components/space/charts/ActionsByWeekdayChart.tsx
src/components/space/charts/ActiveUsersChart.tsx
src/components/space/charts/ItemsByActionChart.tsx
src/components/space/charts/ItemsByUserChart.tsx
src/components/space/charts/MemberActionsChart.tsx
src/components/space/charts/UsersByActionChart.tsx
yarn.lock

feat: arabic view - rtl

---

CHANGELOG.md
cypress/e2e/chartsHeader.cy.ts
mockServer/mockServer.ts
package.json
src/components/common/DateRange.tsx
src/components/context/DataProvider.tsx
src/components/pages/HomePage.tsx
src/components/pages/MyAnalyticsPage.tsx
src/components/space/charts-layout/ActionsLegend.tsx
src/components/space/charts-layout/ChartsHeader.tsx
src/components/space/charts/ActionsByDayChart.tsx
src/components/space/charts/ActionsByTimeOfDayChart.tsx
src/components/space/charts/ActionsByUserChart.tsx
src/components/space/charts/ActionsByWeekdayChart.tsx
src/components/space/charts/ActionsCard.tsx
src/components/space/charts/ActiveUsersCard.tsx
src/components/space/charts/ActiveUsersChart.tsx
src/components/space/charts/TotalActionsByVerbChart.tsx
src/components/space/functionality/ViewSelect.tsx
src/config/selectors.ts
yarn.lock

 feat: add date picker within item pages

---

src/components/space/charts/ActiveUsersCard.tsx

fix: fix number of users today
